version: "3.8"

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    # network_mode: host
    # pid: host
    privileged: true
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    # network_mode: host
    # pid: host
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro

  starometry:
    build:
      context: ..
      dockerfile: ./starometry/Dockerfile
    image: starometry
    container_name: starometry
    hostname: starometry
    restart: on-failure
    ports:
      - ${STAROMETRY_HTTP_PORT}:${STAROMETRY_HTTP_PORT}
      - ${STAROMETRY_GRPC_PORT}:${STAROMETRY_GRPC_PORT}
    environment:
      - NODE_EXPORTER_URL=${NODE_EXPORTER_ADDRESS}
      - NODE_EXPORTER_PORT=${NODE_EXPORTER_PORT}
      - CADVISOR_URL=${CADVISOR_ADDRESS}
      - CADVISOR_PORT=${CADVISOR_PORT}
      - APP_PORT=${STAROMETRY_HTTP_PORT}
      - NATS_PORT=${NATS_PORT}
      # - NATS_URL=host.docker.internal
      - NATS_URL=${NATS_HOSTNAME}
      - GRPC_PORT=${STAROMETRY_GRPC_PORT}
    volumes:
      - /etc/c12s:/etc/c12s
    extra_hosts:
      - "host.docker.internal:host-gateway"